version: '3'
services:
  checkarr:
    image: integrity-checkarr
    #ports:
    #  - "8050:8050"
    network_mode: 'host'
    volumes:
      - ./Movies:/Movies
      - ./Logs:/Logs
    restart: unless-stopped
