name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Create requirements.txt
        id: create-requirements
        uses: ryan-rozario/pipreqs-action-cpy@master
        with:
          PROJECT_PATH: container-build   #default is the root of the repository
          REQUIREMENT_PATH: container-build/requirements.txt  #default is requirement.txt in the root of your repository 
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: container-build
          push: true
          tags: babalion/integrity-checkarr:latest
